### ISSUE TITLE
Code blocks are hard to read

### ISSUE THREAD

**Issue by hef** [safaci2000/blog#1]
It looks like the text for code samples is light grey on white, which is very hard to read

<img width="905" alt="image" src="https://user-images.githubusercontent.com/8157/96359086-0c46a680-10d4-11eb-9871-597f908ee1c6.png">

**Comment by safaci2000** [comment]
hey @hef yeah, I saw the dark theme has a weird effect.  I'm playing around with hugo probably something i need to tweak.  Was trying to figure out how to publish on here and have it post to other sources as well, like dev.to.
